# Generated by Django 5.0.3 on 2024-09-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='models.tagmodel', verbose_name='ManyToManyField to Tag'),
        ),
    ]
