# Generated by Django 5.0.3 on 2024-09-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, to='models.tagmodel', verbose_name='ManyToManyField to Tag'),
        ),
    ]
