# Generated by Django 5.0.3 on 2024-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='content',
            field=models.TextField(max_length=120, verbose_name='comment'),
        ),
    ]
