# Generated by Django 5.0.3 on 2024-10-11 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_productreview_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100, verbose_name='адрес улицы')),
                ('apartment_addres', models.CharField(max_length=100, verbose_name='адрес квартиры')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('zip_code', models.CharField(max_length=100, verbose_name='почтовый индекс')),
                ('phone', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Shipping Adress',
                'verbose_name_plural': 'Shipping Adress',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.shippingadress', verbose_name='shipping address'),
            preserve_default=False,
        ),
    ]
