# Generated by Django 5.0.3 on 2024-10-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('models', '0011_shippingadress_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country', verbose_name='Country'),
        ),
    ]
