# Generated by Django 5.0.3 on 2024-10-11 11:47

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_alter_shippingadress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
