# Generated by Django 5.0.3 on 2024-10-20 10:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_alter_order_shipping_address_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Product'),
        ),
        migrations.CreateModel(
            name='GenerateCodeConfirmationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='A 6-digit confirmation code', max_length=6, verbose_name='Confirmation Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expiry_time', models.DateTimeField(default=datetime.datetime(2024, 10, 20, 10, 44, 46, 703573, tzinfo=datetime.timezone.utc), verbose_name='Expiry Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Confirmation Email Code',
                'verbose_name_plural': 'Confirmation Email Codes',
            },
        ),
    ]
