# Generated by Django 5.0.3 on 2024-10-24 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_remove_order_total_price_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AlterField(
            model_name='generatecodeconfirmationemail',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 11, 57, 56, 284205, tzinfo=datetime.timezone.utc), verbose_name='Expiry Time'),
        ),
    ]
