# Generated by Django 5.0.3 on 2024-10-24 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_user_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecodeconfirmationemail',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 12, 21, 32, 58512, tzinfo=datetime.timezone.utc), verbose_name='Expiry Time'),
        ),
    ]
