# Generated by Django 5.0.3 on 2024-11-02 12:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_order_total_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecodeconfirmationemail',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 12, 42, 36, 96722, tzinfo=datetime.timezone.utc), verbose_name='Expiry Time'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customers',)},
        ),
        migrations.CreateModel(
            name='CheckoutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Date update')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.shippingadress')),
            ],
            options={
                'verbose_name': 'CheckOut',
                'verbose_name_plural': 'CheckOut Many',
            },
        ),
    ]
