# Generated by Django 5.0.3 on 2024-11-02 13:08

import datetime
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_alter_generatecodeconfirmationemail_expiry_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutmodel',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='apartment_addres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='адрес квартиры'),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона'),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='адрес улицы'),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='zip_code',
            field=models.CharField(default=1, max_length=100, verbose_name='почтовый индекс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generatecodeconfirmationemail',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 13, 17, 24, 576594, tzinfo=datetime.timezone.utc), verbose_name='Expiry Time'),
        ),
    ]
