# Generated by Django 5.0.3 on 2024-11-21 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_product_sales_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecodeconfirmationemail',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 13, 50, 24, 740715, tzinfo=datetime.timezone.utc), verbose_name='Expiry Time'),
        ),
    ]
